name: weatherapptest
description: A new Flutter application.


version: 1.0.0+2

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  getflutter: ^1.0.11
  data_connection_checker: ^0.3.4
  flutter_swiper: ^1.1.6
  weather_icons: ^2.0.1
  weather: ^0.9.6
  flutter_custom_clippers: ^1.1.1
  animated_text_kit: ^2.0.0
  intl: ^0.16.1
  sunrise_sunset: "^1.0.2"
  time_formatter: ^1.0.0
  page_transition: ^1.1.5
  swipedetector: ^1.2.0
  lottie: ^0.3.3
  geolocator: ^5.3.1
  http: ^0.12.0+4
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  fonts:
    - family: Montserrat
      fonts:
        - asset: assets/fonts/Montserrat/Montserrat-Regular.ttf
        - asset: assets/fonts/Montserrat/Montserrat-Bold.ttf
    - family: Pacifico
      fonts:
        - asset: assets/fonts/Pacifico-Regular.ttf
    - family: BEYNO
      fonts:
        - asset: assets/fonts/BEYNO.ttf




  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/background/
    - assets/weather_icons/
    - assets/staticWeatherIcons/
    - assets/landingPageAnimation/
    - assets/circularAvatar/
    - images/


  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
